#https://blog.jdblischak.com/posts/circleci-for-r-1/
#NOT_CRAN true should mean all tests run, including skip on cran
version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:4b:83:f1:1b:b4:6b:cd:12:94:df:3f:ac:5f:36:82"
  build:
    docker:
      - image: rocker/verse:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: | 
            R -e 'install.packages("remotes")'
            R -e 'install.packages("covr")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz --no-manual
      - run:
          name: Calculate code coverage
          no_output_timeout: 20m
          command: Rscript -e 'covr::codecov()'
          